/*
 * ArcEmu MMORPG Server
 * Copyright (C) 2005-2007 Ascent Team <http://www.ascentemu.com/>
 * Copyright (C) 2008-2009 <http://www.ArcEmu.org/>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

#ifndef __WORLDSTATE_H
#define __WORLDSTATE_H

/**
 * World PvP
 * Hellfire Peninsula
 */

// Zone ID, used in many places.
#define ZONE_HELLFIRE_PENINSULA									3483

// Tower Counter Value
#define WORLDSTATE_HELLFIRE_ALLIANCE_TOWERS_CONTROLLED			2476
#define WORLDSTATE_HELLFIRE_HORDE_TOWERS_CONTROLLED				2478

// Tower Counter Display
#define WORLDSTATE_HELLFIRE_TOWER_DISPLAY_ALLIANCE				2490
#define WORLDSTATE_HELLFIRE_TOWER_DISPLAY_HORDE					2489

// PvP Capture Bar
#define WORLDSTATE_HELLFIRE_PVP_CAPTURE_BAR_DISPLAY				2473
#define WORLDSTATE_HELLFIRE_PVP_CAPTURE_BAR_VALUE				2474

// The Stadium Control Point
#define WORLDSTATE_HELLFIRE_STADIUM_NEUTRAL						2472
#define WORLDSTATE_HELLFIRE_STADIUM_ALLIANCE					2471
#define WORLDSTATE_HELLFIRE_STADIUM_HORDE						2470

// The Overlook Control Point
#define WORLDSTATE_HELLFIRE_OVERLOOK_NEUTRAL					2482
#define WORLDSTATE_HELLFIRE_OVERLOOK_ALLIANCE					2480
#define WORLDSTATE_HELLFIRE_OVERLOOK_HORDE						2481

// Broken Hill Control Point
#define WORLDSTATE_HELLFIRE_BROKENHILL_NEUTRAL					2485
#define WORLDSTATE_HELLFIRE_BROKENHILL_ALLIANCE					2483
#define WORLDSTATE_HELLFIRE_BROKENHILL_HORDE					2484

/**
 * World PvP
 * Nagrand/Halaa
 */

// Zone ID
#define ZONE_NAGRAND											3518

// Guard Display
#define WORLDSTATE_HALAA_GUARD_DISPLAY_ALLIANCE					2502
#define WORLDSTATE_HALAA_GUARD_DISPLAY_HORDE					2503

// Guard Fields
#define WORLDSTATE_HALAA_GUARDS_REMAINING						2491
#define WORLDSTATE_HALAA_GUARDS_REMAINING_MAX					3493

#define WORLDSTATE_HALAA_TOWER_SLIDER_DISPLAY					2495
#define WORLDSTATE_HALAA_TOWER_SLIDER_POS						2494
#define WORLDSTATE_HALAA_TOWER_SLIDER_N							2497

#define WORLDSTATE_HALAA_WYVERN_NORTH_NEU_H						2762
#define WORLDSTATE_HALAA_WYVERN_NORTH_NEU_A						2662
#define WORLDSTATE_HALAA_WYVERN_NORTH_H							2663
#define WORLDSTATE_HALAA_WYVERN_NORTH_A							2664

#define WORLDSTATE_HALAA_WYVERN_SOUTH_NEU_H						2760
#define WORLDSTATE_HALAA_WYVERN_SOUTH_NEU_A						2670
#define WORLDSTATE_HALAA_WYVERN_SOUTH_H							2668
#define WORLDSTATE_HALAA_WYVERN_SOUTH_A							2669

#define WORLDSTATE_HALAA_WYVERN_WEST_NEU_H						2761
#define WORLDSTATE_HALAA_WYVERN_WEST_NEU_A						2667
#define WORLDSTATE_HALAA_WYVERN_WEST_H							2665
#define WORLDSTATE_HALAA_WYVERN_WEST_A							2666

#define WORLDSTATE_HALAA_WYVERN_EAST_NEU_H						2763
#define WORLDSTATE_HALAA_WYVERN_EAST_NEU_A						2659
#define WORLDSTATE_HALAA_WYVERN_EAST_H							2660
#define WORLDSTATE_HALAA_WYVERN_EAST_A							2661

#define WORLDSTATE_HALAA_HALAA_NEUTRAL							2671
#define WORLDSTATE_HALAA_HALAA_NEU_A							2676
#define WORLDSTATE_HALAA_HALAA_NEU_H							2677
#define WORLDSTATE_HALAA_HALAA_HORDE							2672
#define WORLDSTATE_HALAA_HALAA_ALLIANCE							2673

/**
* World PvP
* Silithus
*/
#define ZONE_SILITHUS											1377

#define WORLDSTATE_SILITHUS_GATHERED_ALLIANCE					2313
#define WORLDSTATE_SILITHUS_GATHERED_HORDE						2314
// really not needed
#define WORLDSTATE_SILITHUS_SILITHYST_MAX						2317

/**
 * World PvP
 * Zangarmarsh 
 */

#define ZONE_ZANGARMARSH										3521

// Tower stuff
#define WORLDSTATE_ZANGARMARSH_EAST_NEUTRAL_MAP					2652
#define WORLDSTATE_ZANGARMARSH_EAST_ALLIANCE_MAP				2650
#define WORLDSTATE_ZANGARMARSH_EAST_HORDE_MAP					2651

#define WORLDSTATE_ZANGARMARSH_EAST_NEUTRAL_UI					2560
#define WORLDSTATE_ZANGARMARSH_EAST_ALLIANCE_UI					2558
#define WORLDSTATE_ZANGARMARSH_EAST_HORDE_UI					2559

#define WORLDSTATE_ZANGARMARSH_WEST_NEUTRAL_MAP					2646
#define WORLDSTATE_ZANGARMARSH_WEST_ALLIANCE_MAP				2644
#define WORLDSTATE_ZANGARMARSH_WEST_HORDE_MAP					2645

#define WORLDSTATE_ZANGARMARSH_WEST_NEUTRAL_UI					2557
#define WORLDSTATE_ZANGARMARSH_WEST_ALLIANCE_UI					2555
#define WORLDSTATE_ZANGARMARSH_WEST_HORDE_UI					2556

// Capture bars
#define WORLDSTATE_ZANGARMARSH_CAPTURE_BAR_DISPLAY_WEST			2527
#define WORLDSTATE_ZANGARMARSH_CAPTURE_BAR_VALUE_WEST			2528

#define WORLDSTATE_ZANGARMARSH_CAPTURE_BAR_DISPLAY_EAST			2533
#define WORLDSTATE_ZANGARMARSH_CAPTURE_BAR_VALUE_EAST			2534

// Flag

// Ally
#define WORLDSTATE_ZANGARMARSH_SCOUT_READY_ALLIANCE				2655
#define WORLDSTATE_ZANGARMARSH_SCOUT_NOT_READY_ALLIANCE			2656

// Horde
#define WORLDSTATE_ZANGARMARSH_SCOUT_READY_HORDE				2658
#define WORLDSTATE_ZANGARMARSH_SCOUT_NOT_READY_HORDE			2657

#define WORLDSTATE_ZANGARMARSH_CITY_NEUTRAL						2647
#define WORLDSTATE_ZANGARMARSH_CITY_ALLIANCE					2648
#define WORLDSTATE_ZANGARMARSH_CITY_HORDE						2649

/**
 * World PvP
 * Terokkar Forest
 */

// Zone ID
#define ZONE_TEROKKAR_FOREST									3519

#define WORLDSTATE_TEROKKAR_TOWER1_NEUTRAL						2681
#define WORLDSTATE_TEROKKAR_TOWER1_ALLIANCE						2683
#define WORLDSTATE_TEROKKAR_TOWER1_HORDE						2682

#define WORLDSTATE_TEROKKAR_TOWER2_NEUTRAL						2686
#define WORLDSTATE_TEROKKAR_TOWER2_ALLIANCE						2684
#define WORLDSTATE_TEROKKAR_TOWER2_HORDE						2685

#define WORLDSTATE_TEROKKAR_TOWER3_NEUTRAL						2690
#define WORLDSTATE_TEROKKAR_TOWER3_ALLIANCE						2688
#define WORLDSTATE_TEROKKAR_TOWER3_HORDE						2689

#define WORLDSTATE_TEROKKAR_TOWER4_NEUTRAL						2696
#define WORLDSTATE_TEROKKAR_TOWER4_ALLIANCE						2694
#define WORLDSTATE_TEROKKAR_TOWER4_HORDE						2695

#define WORLDSTATE_TEROKKAR_TOWER5_NEUTRAL						2693
#define WORLDSTATE_TEROKKAR_TOWER5_ALLIANCE						2691
#define WORLDSTATE_TEROKKAR_TOWER5_HORDE						2692

#define WORLDSTATE_TEROKKAR_ALLIANCE_TOWERS_CONTROLLED			2621
#define WORLDSTATE_TEROKKAR_HORDE_TOWERS_CONTROLLED				2622

#define WORLDSTATE_TEROKKAR_PVP_CAPTURE_BAR_DISPLAY				2623
#define WORLDSTATE_TEROKKAR_PVP_CAPTURE_BAR_VALUE				2625

/**
 * Raid
 * Hyjal map 534
 */
#define WORLDSTATE_HYJAL_ENEMY									2453
#define WORLDSTATE_HYJAL_ENEMYCOUNT								2454
#define WORLDSTATE_HYJAL_WAVES									2842


#endif
