ALTER TABLE spellfixes ADD groupRelation0 int8 UNSIGNED NOT NULL DEFAULT 0; 
ALTER TABLE spellfixes ADD groupRelation1 int8 UNSIGNED NOT NULL DEFAULT 0; 
ALTER TABLE spellfixes ADD groupRelation2 int8 UNSIGNED NOT NULL DEFAULT 0;

