#!/usr/bin/env sh

# SVN Revision Extractor for Unix systems
# Written by Burlex, 2008/02/20

revision=`LC_ALL=C svn info | grep Revision | cut -d' ' -f2`
if [ -z $revision ]; then
	revision=0
fi

echo -e "// This file was automatically generated by the SVN revision extractor.\n"\
"// There is no need to modify it.\n\n"\
"#ifndef SVN_REVISION_H\n"\
"#define SVN_REVISION_H\n\n"\
"static const char * BUILD_TAG = \"`cat ascent-tag`\";\n"\
"static int BUILD_REVISION = $revision;\n\n"\
"#endif // SVN_REVISION_H" > src/ascent-shared/svn_revision.h

echo "1"
