// This file was automatically generated by the SVN revision extractor.
// There is no need to modify it.

#ifndef SVN_REVISION_H
#define SVN_REVISION_H

static const char * BUILD_TAG = "1.4-TRUNK";
static int BUILD_REVISION = 1491;

#endif // SVN_REVISION_H
